<?php
return [
    [
        "name"                  => "Gnocchi al Gorgonzola",
        "ingredients"           => "Gnocchi di patate con salsa cremosa al gorgonzola e noci",
        "price"                 => 1300,
        "visibility"            => true,
        "restaurant_id"         => 1,
    ],
    [
        "name"                  => "Ravioli di Zucca",
        "ingredients"           => "Ravioli ripieni di zucca, serviti con burro e salvia.",
        "price"                 => 1500,
        "visibility"            => true,
        "restaurant_id"         => 1,
    ],
    [
        "name"                  => "Pappardelle al Cinghiale",
        "ingredients"           => "Larghe strisce di pasta con ragù di cinghiale, vino rosso e aromi.",
        "price"                 => 1500,
        "visibility"            => true,
        "restaurant_id"         => 1,
    ],
    [
        "name"                  => "Orecchiette con Cime di Rapa",
        "ingredients"           => "Orecchiette con cime di rapa, aglio peperoncino e olio d'oliva.",
        "price"                 => 1300,
        "visibility"            => true,
        "restaurant_id"         => 1,
    ],
    [
        "name"                  => "Tagliatelle al Tartufo",
        "ingredients"           => "Tagliatelle con salsa al tartufo, spolverate di tartufo fresco.",
        "price"                 => 1500,
        "visibility"            => true,
        "restaurant_id"         => 1,
    ],
    [
        "name"                  => "Pasta alla Norma",
        "ingredients"           => "Pasta condita con salsa di pomodoro, melanzane fritte, ricotta salata e basilico.",
        "price"                 => 1700,
        "visibility"            => true,
        "restaurant_id"         => 2,
    ],
    [
        "name"                  => "Pasta con le Sarde",
        "ingredients"           => "Pasta con sardine fresche, finocchietto selvatico, uvetta, pinoli e cipolla.",
        "price"                 => 1550,
        "visibility"            => true,
        "restaurant_id"         => 2,
    ],
    [
        "name"                  => "Risotto al Nero di Seppia",
        "ingredients"           => "Risotto nero ottenuto dal nero di seppia, arricchito con frutti di mare.",
        "price"                 => 1800,
        "visibility"            => true,
        "restaurant_id"         => 2,
    ],
    [
        "name"                  => "Busiate Trapanesi al Pesto di Mandorle",
        "ingredients"           => "Pasta a spirale con pesto di mandorle, pomodori secchi, basilico e pecorino.",
        "price"                 => 1600,
        "visibility"            => true,
        "restaurant_id"         => 2,
    ],
    [
        "name"                  => "Lasagna al Forno",
        "ingredients"           => "Strati di pasta, ragù di carne, besciamella e formaggio, cotti al forno.",
        "price"                 => 1400,
        "visibility"            => true,
        "restaurant_id"         => 2,
    ],
    [
        "name"                  => "Risotto alla Milanese",
        "ingredients"           => "Risotto giallo al gusto intenso dello zafferano, spesso accompagnato dall'osso con midollo.",
        "price"                 => 1800,
        "visibility"            => true,
        "restaurant_id"         => 3,
    ],
    [
        "name"                  => "Pasta al Pesto Genovese",
        "ingredients"           => "Pasta con pesto di basilico, pinoli, aglio, parmigiano e olio d'oliva.",
        "price"                 => 1500,
        "visibility"            => true,
        "restaurant_id"         => 3,
    ],
    [
        "name"                  => "Farfalle al Salmone",
        "ingredients"           => "Farfalle con salsa al salmone, panna, cipolla e brandy.",
        "price"                 => 1300,
        "visibility"            => true,
        "restaurant_id"         => 3,
    ],
    [
        "name"                  => "Linguine alle Vongole",
        "ingredients"           => "Linguine con vongole fresche, aglio, peperoncino e prezzemolo.",
        "price"                 => 1700,
        "visibility"            => true,
        "restaurant_id"         => 3,
    ],
    [
        "name"                  => "Paccheri Cacio e Pepe",
        "ingredients"           => "Paccheri conditi con pecorino romano e pepe nero.",
        "price"                 => 1850,
        "visibility"            => true,
        "restaurant_id"         => 3,
    ],
    [
        "name"                  => "Margherita",
        "ingredients"           => "Pomodoro, mozzarella fresca, basilico e olio d'oliva.",
        "price"                 => 600,
        "visibility"            => true,
        "restaurant_id"         => 3,
    ],
    [
        "name"                  => "Capricciosa",
        "ingredients"           => "Pomodoro, mozzarella, prosciutto cotto, funghi, carciofi, olive e uova.",
        "price"                 => 700,
        "visibility"            => true,
        "restaurant_id"         => 3,
    ],
    [
        "name"                  => "Quattro Formaggi",
        "ingredients"           => "Mozzarella, gorgonzola, pecorino, e parmigiano.",
        "price"                 => 750,
        "visibility"            => true,
        "restaurant_id"         => 3,
    ],
    [
        "name"                  => "Pepperoni",
        "ingredients"           => "Pomodoro, mozzarella e fette di salame piccante.",
        "price"                 => 700,
        "visibility"            => true,
        "restaurant_id"         => 3,
    ],
    [
        "name"                  => "Prosciutto e Funghi",
        "ingredients"           => "Pomodoro, mozzarella, prosciutto cotto e funghi.",
        "price"                 => 800,
        "visibility"            => true,
        "restaurant_id"         => 3,
    ],
    [
        "name"                  => "Diavola",
        "ingredients"           => "Pomodoro, mozzarella, salame piccante, peperoncino e olive nere.",
        "price"                 => 750,
        "visibility"            => true,
        "restaurant_id"         => 3,
    ],
    [
        "name"                  => "Spaghetti alla Carbonara",
        "ingredients"           => "Spaghetti conditi con uova, pecorino romano, pancetta croccante e pepe nero.",
        "price"                 => 1800,
        "visibility"            => true,
        "restaurant_id"         => 4,
    ],
    [
        "name"                  => "Pasta alla Gricia",
        "ingredients"           => "Pasta condita con pecorino romano, pancetta croccante e pepe nero.",
        "price"                 => 1700,
        "visibility"            => true,
        "restaurant_id"         => 4,
    ],
    [
        "name"                  => "Risotto al Nero di Seppia",
        "ingredients"           => "Risotto nero ottenuto dall'uso del nero di seppia, con calamari, prezzemolo e aglio.",
        "price"                 => 2000,
        "visibility"            => true,
        "restaurant_id"         => 4,
    ],
    [
        "name"                  => "Penne all'Arrabbiata",
        "ingredients"           => "Penne con salsa piccante a base di pomodoro, peperoncino, aglio e olio d'oliva.",
        "price"                 => 1700,
        "visibility"            => true,
        "restaurant_id"         => 4,
    ],
    [
        "name"                  => "Linguine alle Vongole",
        "ingredients"           => "Linguine con vongole fresche, aglio, peperoncino e prezzemolo.",
        "price"                 => 1850,
        "visibility"            => true,
        "restaurant_id"         => 4,
    ],
    [
        "name"                  => "Margherita",
        "ingredients"           => "Pomodoro, mozzarella fresca, basilico e olio d'oliva.",
        "price"                 => 650,
        "visibility"            => true,
        "restaurant_id"         => 4,
    ],
    [
        "name"                  => "Capricciosa",
        "ingredients"           => "Pomodoro, mozzarella, prosciutto cotto, funghi, carciofi, olive e uova.",
        "price"                 => 800,
        "visibility"            => true,
        "restaurant_id"         => 4,
    ],
    [
        "name"                  => "Quattro Stagioni",
        "ingredients"           => "Pomodoro, mozzarella, prosciutto cotto, funghi, carciofi e olive nere, suddivisa in quadranti diversi.",
        "price"                 => 750,
        "visibility"            => true,
        "restaurant_id"         => 4,
    ],
    [
        "name"                  => "Bianca",
        "ingredients"           => "Mozzarella, ricotta, aglio, spinaci e olio d'oliva.",
        "price"                 => 700,
        "visibility"            => true,
        "restaurant_id"         => 4,
    ],
    [
        "name"                  => "Tonno e Cipolla",
        "ingredients"           => "Pomodoro, mozzarella, tonno, cipolla rossa e olive.",
        "price"                 => 800,
        "visibility"            => true,
        "restaurant_id"         => 4,
    ],
    [
        "name"                  => "Calzone",
        "ingredients"           => "Ripieno di pomodoro, mozzarella, salame, prosciutto cotto e altri ingredienti a scelta, piegato a mezzaluna e cotto al forno.",
        "price"                 => 800,
        "visibility"            => true,
        "restaurant_id"         => 4,
    ],
    [
        "name"                  => "Pasta alla Norma",
        "ingredients"           => "Pasta condita con salsa di pomodoro, melanzane fritte, ricotta salata e basilico.",
        "price"                 => 1200,
        "visibility"            => true,
        "restaurant_id"         => 5,
    ],
    [
        "name"                  => "Pasta con la Mollica",
        "ingredients"           => "Pasta condita con mollica di pane tostato, acciughe, aglio, prezzemolo e peperoncino.",
        "price"                 => 1300,
        "visibility"            => true,
        "restaurant_id"         => 5,
    ],
    [
        "name"                  => "Pasta c'anciova e Muddica Atturrata",
        "ingredients"           => "Pasta con acciughe e mollica di pane tostato.",
        "price"                 => 1300,
        "visibility"            => true,
        "restaurant_id"         => 5,
    ],
    [
        "name"                  => "Timballo di Anelletti al Forno",
        "ingredients"           => "Anelletti al forno con ragù di carne, piselli, melanzane e formaggio.",
        "price"                 => 1300,
        "visibility"            => true,
        "restaurant_id"         => 5,
    ],
    [
        "name"                  => "Lasagna al Forno",
        "ingredients"           => "Strati di pasta, ragù di carne, besciamella e formaggio, cotti al forno.",
        "price"                 => 1350,
        "visibility"            => true,
        "restaurant_id"         => 5,
    ],
    [
        "name"                  => "Shabu shabu",
        "price"                 => 1550,
        "ingredients"           => "manzo, scarola, germogli di soia, funghi Shiitake, funghi Orecchione, cipollotti, carote, brodo di carne,  e per la salsa una miscela di salsa di soia,succo di limone o lime, brodo dashi",
        "visibility"            => true,
        "restaurant_id"         => 6,
    ],
    [
        "name"                  => "Nigiri- tonno kataifi",
        "price"                 => 450,
        "ingredients"           => "riso, tonno scottato, philadelphia, kataifi, teriyaki",
        "visibility"            => true,
        "restaurant_id"         => 6,
    ],
    [
        "name"                  => "Futomaki",
        "price"                 => 450,
        "ingredients"           => "polpetta di riso cilindrica, spessa due o tre centimetri e larga quattro o cinque centimetri, con un'alga nori all'esterno. All'interno condita con pezzetti di salmone crudo, avocado e philadelphia",
        "visibility"            => false,
        "restaurant_id"         => 6,
    ],
    [
        "name"                  => "Hosomaki- Tempura Salmone",
        "price"                 => 600,
        "ingredients"           => "salmone tutto in tempura, teriyaki",
        "visibility"            => true,
        "restaurant_id"         => 6,
    ],
    [
        "name"                  => "Tartare",
        "price"                 => 1050,
        "ingredients"           => "gambero rosso, pomodoro, avocado, olio d'oliva, riso",
        "visibility"            => true,
        "restaurant_id"         => 6,
    ],
    [
        "name"                  => "Okonomiyaki - frittatine giapponesi",
        "price"                 => 650,
        "ingredients"           => "uova, farina, verdure a scelta, calamari essiccati, alga nori, e fiocchi di tonno essiccato, maionese, olio di semi",
        "visibility"            => true,
        "restaurant_id"         => 6,
    ],
    [
        "name"                  => "Ramen di Maiale",
        "price"                 => 1000,
        "ingredients"           => "alga kombu, katsuobushi, ossa di un pollo intero, cipollotto, fette di zenzero, pezzi di aglio, lonza o spalla di maiale, uova, salsa di soia",
        "visibility"            => true,
        "restaurant_id"         => 7,
    ],
    [
        "name"                  => "Ramen Vegetariano",
        "price"                 => 1250,
        "ingredients"           => "alga kombu, uova, cipollotti, unghi shiitake, salsa Doubanjiang, miso giapponese, sale, pepe, zenzero fresco",
        "visibility"            => true,
        "restaurant_id"         => 7,
    ],
    [
        "name"                  => "Bibimbap",
        "price"                 => 750,
        "ingredients"           => "riso, mano tritato, uova, zucchero, carote, spinaci, germogli di soia, olio, peperoncino, semi di sesamo",
        "visibility"            => true,
        "restaurant_id"         => 7,
    ],
    [
        "name"                  => "Japchae",
        "price"                 => 900,
        "ingredients"           => " noodles di patate, scalogni, spinaci, funghi, carota, peperone rosso, zucchina, filetto di manzo o maiale",
        "visibility"            => true,
        "restaurant_id"         => 7,
    ],
    [
        "name"                  => "Yachaejeon",
        "price"                 => 250,
        "ingredients"           => "carota, zucchine, cipolla, funghi, farina, acqua, sale, olio, salsa di soia, aceto di riso",
        "visibility"            => true,
        "restaurant_id"         => 7,
    ],
    [
        "name"                  => "Yaki Udon",
        "price"                 => 550,
        "ingredients"           => "Udon, verdure miste, salsa di soia, zenzero grattuggiato, (l'aggiunta di carne di maiale è opzionale)",
        "visibility"            => false,
        "restaurant_id"         => 7,
    ],
    [
        "name"                  => "Ravioli Cinesi",
        "price"                 => 750,
        "ingredients"           => "farina, acqua a temperatura ambiente, sale q.b., germogli di soia, verza, carota, cipollotto, zenzero fresco, salsa di soia, olio di semi di girasole oppure olio di sesamo",
        "visibility"            => true,
        "restaurant_id"         => 8,
    ],
    [
        "name"                  => "Involtini Primavera",
        "price"                 => 200,
        "ingredients"           => "carta di riso, carote, patate, verza, germogli di soia, cipollotti",
        "visibility"            => true,
        "restaurant_id"         => 8,
    ],
    [
        "name"                  => "Riso alla cantonese",
        "price"                 => 650,
        "ingredients"           => "riso, piselli, olio di cocco, uova, straccetti di prosciutto",
        "visibility"            => true,
        "restaurant_id"         => 8,
    ],
    [
        "name"                  => "Vitello con Riso",
        "price"                 => 800,
        "ingredients"           => "riso, vitello, porro, peperoni, cipolla, salsa di soia",
        "visibility"            => false,
        "restaurant_id"         => 8,
    ],
    [
        "name"                  => "Gnocchi di riso",
        "price"                 => 750,
        "ingredients"           => "farina di riso, farina 00, acqua, zucchine, carote, zenzero, cipollotto, salsa di soia",
        "visibility"            => true,
        "restaurant_id"         => 8,
    ],
    [
        "name"                  => "Pollo all'arancia",
        "price"                 => 800,
        "ingredients"           => "pollo, salsa di sioia, zucchero di canna, peperoncino, aglio, aceto di riso, zenzero, semi di sesamo, maizena, arance, olio",
        "visibility"            => false,
        "restaurant_id"         => 8,
    ],
    [
        "name"                  => "Pad Thai",
        "price"                 => 1000,
        "ingredients"           => "spaghetti di riso, gamberi, tofu, uova, germogli di soia, salsa di pesce, zucchero, aceto",
        "visibility"            => true,
        "restaurant_id"        => 9,
    ],
    [
        "name"                  => "Tom Yum",
        "price"                 => 950,
        "ingredients"           => "gamberetti sgusciati, aglio, cipolla, peperone verde, zenzero, curry, brodo vegetale, latte di cocco, noce di burro, coriandolo fresco e succo di limone",
        "visibility"            => true,
        "restaurant_id"         => 9,
    ],
    [
        "name"                  => "Gai Pad (pollo con anacardi)",
        "price"                 => 600,
        "ingredients"           => "petto di pollo, cipolla, anacardi, aglio, farina, olio, salsa di soia, salsa di ostrica, zucchero, acqua, sale, pepe",
        "visibility"            => true,
        "restaurant_id"         => 9,
    ],
    [
        "name"                  => "Khao Pad",
        "price"                 => 850,
        "ingredients"           => "riso, cipollotto, uova, basilico, gamberi o pollo, lime",
        "visibility"            => true,
        "restaurant_id"         => 9,
    ],
    [
        "name"                  => "Yum Nua",
        "price"                 => 550,
        "ingredients"           => "manzo, verdure di stagione",
        "visibility"            => true,
        "restaurant_id"         => 9,
    ],
    [
        "name"                  => "Yum Woon Sen",
        "price"                 => 900,
        "ingredients"           => "macinato di maiale, gamberi, pomodori, cipollotti, salsa di pesce, succo di lime, zucchero, noodles di riso",
        "visibility"            => true,
        "restaurant_id"         => 9,
    ],
    [
        "name"                  => "Chicken Makhani-Pollo al burro",
        "price"                 => 1250,
        "ingredients"           => "pollo, burro Ghee, zenzero, cipolla, aglio, pomodoro, yogurt, curcuma, curry, coriandolo, garam Masala, sale",
        "visibility"            => true,
        "restaurant_id"         => 10,
    ],
    [
        "name"                  => "Samosa",
        "price"                 => 300,
        "ingredients"           => "farina, burro, patate, carote, piselli, zenzero, peperoncino, amchoor, garam Masala, sale",
        "visibility"            => true,
        "restaurant_id"         => 10,
    ],
    [
        "name"                  => "Pakora",
        "price"                 => 250,
        "ingredients"           => "patate, mais, cipolla, peperoni, spinaci, farina di ceci, peperoncino, limone, olio",
        "visibility"            => true,
        "restaurant_id"         => 10,
    ],
    [
        "name"                  => "Biryani di agnello",
        "price"                 => 1550,
        "ingredients"           => "agnello, riso, mais, peperoncino, cumino, zenzero, cannella, aglio, cipolle, cardamomo, alloro, zafferano, olio, sale",
        "visibility"            => false,
        "restaurant_id"         => 10,
    ],
    [
        "name"                  => "Pad Thai",
        "price"                 => 950,
        "ingredients"           => "spaghetti di riso, gamberi, tofu, uova, germogli di soia, salsa di pesce, zucchero, aceto",
        "visibility"            => true,
        "restaurant_id"         => 10,
    ],
    [
        "name"                  => "Tom Yum",
        "price"                 => 1050,
        "ingredients"           => "gamberetti sgusciati, aglio, cipolla, peperone verde, zenzero, curry, brodo vegetale, latte di cocco, noce di burro, coriandolo fresco e succo di limone",
        "visibility"            => true,
        "restaurant_id"         => 10,
    ],
    [
        "name"                  => "dakgangjeong o pollo fritto coreano",
        "price"                 => 850,
        "ingredients"           => "pollo, verdure miste, zenzero, sciroppo di amido di mais, aglio, aceto di mele, senape, peperoncino, arachidi tostate",
        "visibility"            => true,
        "restaurant_id"         => 11,
    ],
    [
        "name"                  => "Involtini Primavera",
        "price"                 => 200,
        "ingredients"           => "carta di riso, carote, patate, verza, germogli di soia, cipollotti",
        "visibility"            => true,
        "restaurant_id"         => 11,
    ],
    [
        "name"                  => "Ravioli Cinesi al vapore",
        "price"                 => 750,
        "ingredients"           => "farina, acqua a temperatura ambiente, sale q.b., germogli di soia, verza, carota, cipollotto, zenzero fresco, salsa di soia, olio di semi di girasole oppure olio di sesamo",
        "visibility"            => true,
        "restaurant_id"         => 11,
    ],
    [
        "name"                  => "Mandu",
        "price"                 => 650,
        "ingredients"           => "farina, uovo, carne, tofu, vermicelli di riso, cipolla, salsa di soia, pepe",
        "visibility"            => true,
        "restaurant_id"         => 11,
    ],
    [
        "name"                  => "Gimbap",
        "price"                 => 850,
        "ingredients"           => "riso, olio di sesamo, se,i di sesamo, spinaci, surimi, uovo, foglie d'alga, ravanello",
        "visibility"            => true,
        "restaurant_id"         => 11,
    ],
    [
        "name"                  => "4 Gusti",
        "price"                 => 700,
        "ingredients"           => "Passata di pomodoro, cotto, olive, funghi, carciofi, mozzarella",
        "visibility"            => true,
        "restaurant_id"        => 12,

    ],
    [
        "name"                  => "Margherita",
        "price"                 => 500,
        "ingredients"           => "passata di pomodoro, mozzarella, basilico",
        "visibility"            => true,
        "restaurant_id"        =>  12,

    ],
    [
        "name"                  => "Diavola",
        "price"                 => 700,
        "ingredients"           => "Passata di pomorodo, Salame piccante, mozzarella, origano",
        "visibility"            =>  true,
        "restaurant_id"        =>  12,

    ],
    [
        "name"                  => "Profumo Di Campagna",
        "price"                 => 1000,
        "ingredients"           => "passata di pomodoro, cipolla, olive, salame piccante ,olio con aglio, origano",
        "visibility"            => true,
        "restaurant_id"        =>  12,

    ],
    [
        "name"                  => "Asineddro",
        "price"                 => 1000,
        "ingredients"           => "mortadella d'asino ragusano, mozzarella,granella di pistacchio, stracciatella",
        "visibility"            => true,
        "restaurant_id"        =>  12,

    ],
    [
        "name"                  => "TunnuTunnu",
        "price"                 => 900,
        "ingredients"           => "porchetta di tonno, mozzarella,olio al limone, rucola",
        "visibility"            => false,
        "restaurant_id"        =>  12,
    ],
    [
        "name"                  => "Margherita",
        "price"                 => 500,
        "ingredients"           => "passata di pomodoro, mozzarella, basilico",
        "visibility"            => true,
        "restaurant_id"        =>  13,
    ],
    [
        "name"                  => "Diavola",
        "price"                 => 700,
        "ingredients"           => "Passata di pomorodo, Salame piccante, mozzarella,origano",
        "visibility"            => false,
        "restaurant_id"        =>  13,
    ],
    [
        "name"                  => "Siciliana",
        "price"                 => 600,
        "ingredients"           => "Passata Pomodoro, Ciliegino, Pecorino, Olio con aglio, origano, prezzemolo",
        "visibility"            => true,
        "restaurant_id"        =>  13,
    ],
    [
        "name"                  => "Schola",
        "price"                 => 1200,
        "ingredients"           => "matarocco, tonno fresco, mollica tostata, olio con aglio, menta",
        "visibility"            => false,
        "restaurant_id"        =>  13,
    ],
    [
        "name"                  => "Ciuri D'estate",
        "price"                 => 900,
        "ingredients"           => "Crema di zucca, guanciale, fiori di zucca fritti, burrata",
        "visibility"            => true,
        "restaurant_id"        =>  13,
    ],

    [
        "name"                  => "Margherita",
        "price"                 => 500,
        "ingredients"           => "passata di pomodoro, mozzarella, basilico",
        "visibility"            => true,
        "restaurant_id"        => 14,
    ],

    [
        "name"                  => "Diavola",
        "price"                 => 700,
        "ingredients"           => "Passata di pomorodo, Salame piccante, mozzarella, origano",
        "visibility"            => false,
        "restaurant_id"        =>  14,
    ],

    [
        "name"                  => "Number ",
        "price"                 => 900,
        "ingredients"           => "gamberi, vongole, matarocco, mozzarella, olio con aglio, mollica tostata",
        "visibility"            => true,
        "restaurant_id"        => 14,
    ],

    [
        "name"                  => "ZioEnzo",
        "price"                 => 1200,
        "ingredients"           => "Passata di pomodoro, mozzarella, melenzane, parmigiano, patatine fritte, salsiccia, cipolla, mollica tostata",
        "visibility"            => true,
        "restaurant_id"        =>  14,
    ],
    [
        "name"                  => "Parmigiana",
        "price"                 => 600,
        "ingredients"           => "Passata di pomodoro, mozzarella, melenzane, parmigiano, cotto, basilico",
        "visibility"            => true,
        "restaurant_id"        =>  14,
    ],
    [
        "name"                  => "Gelato al Cioccolato",
        "price"                 => 300,
        "ingredients"           => "Latte, cacao, zucchero",
        "visibility"            => true,
        "restaurant_id"         => 15,

    ],
    [
        "name"                  => "Gelato Fiordilatte",
        "price"                 => 300,
        "ingredients"           => "Latte, zucchero, panna",
        "visibility"            => true,
        "restaurant_id"         =>  15,

    ],
    [
        "name"                  => "Gelato alla Crema",
        "price"                 => 300,
        "ingredients"           => "Latte, uova, zucchero",
        "visibility"            =>  true,
        "restaurant_id"         =>  15,

    ],
    [
        "name"                  => "Cannolo alla Ricotta",
        "price"                 => 400,
        "ingredients"           => "Cialda fritta con ripieno alla ricotta",
        "visibility"            => true,
        "restaurant_id"         =>  15,

    ],
    [
        "name"                  => "Cassata",
        "price"                 => 500,
        "ingredients"           => "Torta a base di ricotta, pan di spagna, pasta reale, frutta candita e glassa",
        "visibility"            => true,
        "restaurant_id"         =>  15,

    ],
    [
        "name"                  => "Brioche",
        "price"                 => 200,
        "ingredients"           => "Soffice brioche da accompagnare al tuo gelato",
        "visibility"            => true,
        "restaurant_id"         =>  15,

    ],
    [
        "name"                  => "Sigarette",
        "price"                 => 100,
        "ingredients"           => "Cialda al burro con crema di ricotta",
        "visibility"            => true,
        "restaurant_id"         =>  16,

    ],
    [
        "name"                  => "Granita alla Mandorla",
        "price"                 => 300,
        "ingredients"           => "Pasta di mandorle, zucchero, mandorle",
        "visibility"            => true,
        "restaurant_id"         =>  16,

    ],
    [
        "name"                  => "Granita al Pistacchio",
        "price"                 => 300,
        "ingredients"           => "Pistacchi, zucchero",
        "visibility"            => true,
        "restaurant_id"         =>  16,

    ],
    [
        "name"                  => "Granita ai Gelsi",
        "price"                 => 300,
        "ingredients"           => "Gelsi, zucchero",
        "visibility"            => false,
        "restaurant_id"         =>  16,

    ],
    [
        "name"                  => "Brioche",
        "price"                 => 300,
        "ingredients"           => "Soffice brioche da accompagnare al tuo gelato",
        "visibility"            => true,
        "restaurant_id"         =>  16,

    ],
    [
        "name"                  => "Brioche",
        "price"                 => 300,
        "ingredients"           => "Soffice brioche da accompagnare al tuo gelato",
        "visibility"            => true,
        "restaurant_id"         =>  16,

    ],
    [
        "name"                  => "Iris",
        "price"                 => 500,
        "ingredients"           => "Pasta lievitata ripiena di crema alla ricotta e fritta",
        "visibility"            => true,
        "restaurant_id"         => 16,

    ],
    [
        "name"                  => "Pasta di Mandorle",
        "price"                 => 200,
        "ingredients"           => "Mandorle, uovo, zucchero, miele",
        "visibility"            => true,
        "restaurant_id"         =>  17,

    ],
    [
        "name"                  => "Minne di Sant'Agata ",
        "price"                 => 400,
        "ingredients"           => "Pasta frolla con ripieno di ricotta ricoperta da glassa",
        "visibility"            => true,
        "restaurant_id"         => 17,

    ],
    [
        "name"                  => "Cassata",
        "price"                 => 500,
        "ingredients"           => "Torta a base di ricotta, pan di spagna, pasta reale, frutta candita e glassa",
        "visibility"            => true,
        "restaurant_id"         =>  17,

    ],
    [
        "name"                  => "Iris",
        "price"                 => 500,
        "ingredients"           => "Pasta lievitata ripiena di crema alla ricotta e fritta",
        "visibility"            => false,
        "restaurant_id"         =>  17,
    ],
    [
        "name"                  => "Frutta Martorana",
        "price"                 => 400,
        "ingredients"           => "Farina di mandorle, zucchero",
        "visibility"            => true,
        "restaurant_id"         =>  17,
    ],
    [
        "name"                  => "Babà",
        "price"                 => 200,
        "ingredients"           => "Dolce lievitato bagnato con rum ",
        "visibility"            => true,
        "restaurant_id"         =>  17,
    ],
    [
        "name"                  => "Profiteroles al Cioccolato",
        "price"                 => 600,
        "ingredients"           => "Golosi bignè ripieni di crema Chantilly, ricoperti con cioccolato fondente ",
        "visibility"            => true,
        "restaurant_id"         =>  17,
    ],   [
        "name"                  => "Gyoza di Verdure",
        "price"                 => 400,
        "ingredients"           => "Ravioni al vapore con funghi asiatici cavolo cappuccio e carote",
        "visibility"            => true,
        "restaurant_id"         => 18,
    ],
    [
        "name"                  => "Zuppa di miso Tofu",
        "price"                 => 300,
        "ingredients"           => "Zuppa di miso con alghe, tofu e erba cipollina",
        "visibility"            => true,
        "restaurant_id"         => 18,
    ],
    [
        "name"                  => "Zuppa Agropiccante",
        "price"                 => 400,
        "ingredients"           => "Zuppa con pollo bambù, tofu, uova e funghi",
        "visibility"            => true,
        "restaurant_id"         => 18,
    ],
    [
        "name"                  => "Riso Cantonese",
        "price"                 => 400,
        "ingredients"           => "uova, piselli, prosciutto",
        "visibility"            => true,
        "restaurant_id"         => 18,
    ],
    [
        "name"                  => "Pollo Mandorle",
        "price"                 => 500,
        "ingredients"           => "carote e bambù",
        "visibility"            => true,
        "restaurant_id"         => 18,
    ],
    [
        "name"                  => "Panino Kebab",
        "price"                 => 500,
        "ingredients"           => "Lattuga, radicchio, carote, pomodoro, yogurt e arissa",
        "visibility"            => true,
        "restaurant_id"         => 19,
    ],
    [
        "name"                  => "Piadina Kebab",
        "price"                 => 600,
        "ingredients"           => "Lattuga, radicchio, carote, pomodoro, yogurt e arissa",
        "visibility"            => true,
        "restaurant_id"         => 19,
    ],
    [
        "name"                  => "Stinco di Maiale",
        "price"                 => 1000,
        "ingredients"           => "Con Patate al Forno o Fritte",
        "visibility"            => true,
        "restaurant_id"         => 19,
    ],
    [
        "name"                  => "Pollo alla Brace",
        "price"                 => 750,
        "ingredients"           => "Con Patate al Forno o Fritte",
        "visibility"            => true,
        "restaurant_id"         => 19,
    ],
    [
        "name"                  => "Alette di Pollo",
        "price"                 => 1500,
        "ingredients"           => "1 kg",
        "visibility"            => true,
        "restaurant_id"         => 19,
    ],
    [
        "name"                  => "America",
        "price"                 => 750,
        "ingredients"           => "pomodoro, mozzarella, uovo, bacon e wurstel",
        "visibility"            => true,
        "restaurant_id"         => 20,
    ],
    [
        "name"                  => "Calabrese",
        "price"                 => 700,
        "ingredients"           => "pomodoro, mozzarella, salame, piccante, peperoni e cipolla",
        "visibility"            => true,
        "restaurant_id"         => 20,
    ],
    [
        "name"                  => "Francese",
        "price"                 => 600,
        "ingredients"           => "pomodoro, mozzarella, prosciutto crudo",
        "visibility"            => true,
        "restaurant_id"         => 20,
    ],
    [
        "name"                  => "Oasi",
        "price"                 => 650,
        "ingredients"           => "pomodoro, mozzarella, prosciutto cotto, gorgonzola, olive e salame piccante",
        "visibility"            => true,
        "restaurant_id"         => 20,
    ],
    [
        "name"                  => "Tonno",
        "price"                 => 700,
        "ingredients"           => "pomodoro, mozzarella e tonno",
        "visibility"            => true,
        "restaurant_id"         => 20,
    ],
    [
        "name"                  => "Suli Salmone",
        "price"                 => 990,
        "ingredients"           => "Riso Bianco, Juicy Salmon, Avocado Hass, Edamame, Cavolo Rosso, Salsa Speciale, Crema di Avocado, Sesamo",
        "visibility"            => true,
        "restaurant_id"         => 21,
    ],
    [
        "name"                  => "Spicy Tuna",
        "price"                 => 1090,
        "ingredients"           => "Riso Bianco, Tonno, Goma Wakame, Cavolo Rosso, Carote, Cetrioli, Salsa Ponzu, Salsa Spicy Peanuts, Jalapeño, Cipolla Croccante, Tobiko, Sesamo",
        "visibility"            => true,
        "restaurant_id"         => 21,
    ],
    [
        "name"                  => "Vegan",
        "price"                 => 990,
        "ingredients"           => "Quinoa, Tofu Grigliato Bio, Ceci, Carote, Avocado Hass, Salsa Teriyaki, Patata Dolce Croccante, Sesamo",
        "visibility"            => true,
        "restaurant_id"         => 21,
    ],
    [
        "name"                  => "Mango e Lime",
        "price"                 => 400,
        "ingredients"           => "Mini Fruit Bowl",
        "visibility"            => true,
        "restaurant_id"         => 21,
    ],
    [
        "name"                  => "Super Protein",
        "price"                 => 1090,
        "ingredients"           => "Quinoa e Fresh Baby Spinach, Pollo Teriyaki e Zenzero, Edamame, Avocado Hass, Pomodorini Datterino, Olio EVO Aromatizzato al Limone, Grana Padano in Scaglie, Mandorle, Sesamo",
        "visibility"            => true,
        "restaurant_id"         => 21,
    ],
    [
        "name"                  => "Goma Wakame",
        "price"                 => 300,
        "ingredients"           => "alghe verdi con salsa ponzu",
        "visibility"            => true,
        "restaurant_id"         => 22,
    ],
    [
        "name"                  => "Pollo con funghi bambù",
        "price"                 => 600,
        "ingredients"           => "pollo saltato con verdute miste",
        "visibility"            => true,
        "restaurant_id"         => 22,
    ],
    [
        "name"                  => "Pollo al Limone",
        "price"                 => 600,
        "ingredients"           => "pollo saltato con salsa al limone",
        "visibility"            => true,
        "restaurant_id"         => 22,
    ],
    [
        "name"                  => "Manzo alla piastra",
        "price"                 => 700,
        "ingredients"           => "bambù, cipolla e peperoni",
        "visibility"            => true,
        "restaurant_id"         => 22,
    ],
    [
        "name"                  => "Maiale in salsa Agrodolce",
        "price"                 => 600,
        "ingredients"           => "maiale impanato e saltato in salsa agrodolce",
        "visibility"            => true,
        "restaurant_id"         => 22,
    ],
    [
        "name"                  => "Margherita",
        "price"                 => 600,
        "ingredients"           => "pomodoro e mozzarella fiordilatte",
        "visibility"            => true,
        "restaurant_id"         => 23,
    ],
    [
        "name"                  => "Napoli",
        "price"                 => 600,
        "ingredients"           => "pomodoro, mozzarella fiordilatte, filetti di acciughe e origano",
        "visibility"            => true,
        "restaurant_id"         => 23,
    ],
    [
        "name"                  => "Mascalzone",
        "price"                 => 700,
        "ingredients"           => "pomodoro, mozzarella fiordilatte e prosciutto cotto",
        "visibility"            => true,
        "restaurant_id"         => 23,
    ],
    [
        "name"                  => "Kebab",
        "price"                 => 900,
        "ingredients"           => "pomodoro, mozzarella fiordilatte, kebab e salsa yogurt",
        "visibility"            => true,
        "restaurant_id"         => 23,
    ],
    [
        "name"                  => "Panino Kebab",
        "price"                 => 450,
        "ingredients"           => "Lattuga, radicchio, carote, pomodoro, yogurt e arissa",
        "visibility"            => true,
        "restaurant_id"         => 23,
    ],
    [
        "name"                  => "Involtini Primavera",
        "price"                 => 150,
        "ingredients"           => "verdure e carne di maiale",
        "visibility"            => true,
        "restaurant_id"         => 24,
    ],
    [
        "name"                  => "Involtini Gamberi",
        "price"                 => 250,
        "ingredients"           => "gamberi e porro",
        "visibility"            => true,
        "restaurant_id"         => 24,
    ],
    [
        "name"                  => "Crocchette di patate con gamberi",
        "price"                 => 400,
        "ingredients"           => "1 kg",
        "visibility"            => true,
        "restaurant_id"         => 24,
    ],
    [
        "name"                  => "Poke 1",
        "price"                 => 900,
        "ingredients"           => "Pokè con Riso, Pomodorino, Fagiolini di Soia, Salmone, Mais, Avocado e Uova di Quaglia",
        "visibility"            => true,
        "restaurant_id"         => 24,
    ],
    [
        "name"                  => "Poke 2",
        "price"                 => 900,
        "ingredients"           => "Pokè con Riso, Pomodorino, Fagiolini di Soia, Mais, Avocado, Rucola, Wakame e Mango",
        "visibility"            => true,
        "restaurant_id"         => 24,
    ],
    [
        "name"                  => "Patatine Fritte",
        "price"                 => 150,
        "ingredients"           => "vaschetta media",
        "visibility"            => true,
        "restaurant_id"         => 25,
    ],
    [
        "name"                  => "Anelli di Cipolla",
        "price"                 => 300,
        "ingredients"           => "vaschetta media",
        "visibility"            => true,
        "restaurant_id"         => 25,
    ],
    [
        "name"                  => "Misto Caldo",
        "price"                 => 400,
        "ingredients"           => "Panelle, crocchè e patatine",
        "visibility"            => true,
        "restaurant_id"         => 25,
    ],
    [
        "name"                  => "Mozzarelline Panate",
        "price"                 => 300,
        "ingredients"           => "10 pezzi",
        "visibility"            => true,
        "restaurant_id"         => 25,
    ],
    [
        "name"                  => "Misto Fritto Pollo Per 2 Persone",
        "price"                 => 800,
        "ingredients"           => "nuggets di pollo, ali babà, mozzarelline panate, olive ascolane e patatine",
        "visibility"            => true,
        "restaurant_id"         => 25,
    ],
];
