<?php
return [
    [
        //0
        "user_id"   => 1,
        "rest_name" => "Trattoria del Buongusto",
        "address"   => "Corso Calatafimi, 26",
        "vat"       => "01765242501",
        "img"       => "trattoriadelbuongusto.png",
        "types"     => [2, 1],
    ],
    [
        "user_id"   => 2,
        "rest_name" => "Osteria La Tradizione",
        "address"   => "Via Paolo Perez, 12",
        "vat"       => "01765242502",
        "img"       => "latradizione.png",
        "types"     => [2],
    ],
    [
        "user_id"   => 3,
        "rest_name" => "Ristorante La Piazza",
        "address"   => "P.za Indipendenza, 25",
        "vat"       => "01765242503",
        "img"       => "lapiazza.png",
        "types"     => [2, 1],
    ],
    [
        "user_id"   => 4,
        "rest_name" => "Cucina Italiana da Marco",
        "address"   => "Via Paolo Rubens, 8",
        "vat"       => "01765242504",
        "img"       => "damarco.png",
        "types"     => [2],
    ],
    [
        "user_id"   => 5,
        "rest_name" => "Sapori di Sicilia Trattoria",
        "address"   => "Via dei Nebrodi, 67",
        "vat"       => "01765242505",
        "img"       => "saporidisicilia.png",
        "types"     => [2],
    ],
    [
        //5  
        "user_id"   => 6,
        "rest_name" => "Yuki Sushi",
        "address"   => "Via Pier Santi Mattarella, 90",
        "vat"       => "15745098238",
        "img"       => "yuki-sushi.png",
        "types"     => [4],
    ],
    [
        "user_id"   => 7,
        "rest_name" => "BriccoMatto - La bottega dell'Asia",
        "address"   => "Corso dei Mille, 80",
        "vat"       => "25922458998",
        "img"       => "bricco-matto.png",
        "types"     => [5, 4],
    ],
    [
        "user_id"   => 8,
        "rest_name" => "Jiajia - Ristorante Cinese",
        "address"   => "Piazza Verdi, 55",
        "vat"       => "32324987621",
        "img"       => "jia-jia.png",
        "types"     => [5],
    ],
    [
        "user_id"   => 9,
        "rest_name" => "Siam thai Food",
        "address"   => "via Carmelo Pardi, 64",
        "vat"       => "98436556687",
        "img"       => "thaifood.png",
        "types"     => [8],
    ],
    [
        "user_id"   => 10,
        "rest_name" => "Indo-Thai food",
        "address"   => "Via Paternò, 30",
        "vat"       => "36664697429",
        "img"       => "indothaifood.png",
        "types"     => [6, 8],
    ],
    [
        "user_id"   => 11,
        "rest_name" => "Hobento",
        "address"   => "Via Libertà, 455",
        "vat"       => "10007543295",
        "img"       => "hobento.png",
        "types"     => [7, 4],
    ],
    [
        //11  
        "user_id"   => 12,
        "rest_name" => "Pizzeria Mille Gusti",
        "address"   => "Via ciavolotto, 255/E",
        "vat"       => "14589785235",
        "img"       => "pizzeriamillegusti.png",
        "types"     => [1],
    ],
    [
        "user_id"   => 13,
        "rest_name" => "Mille Sapori",
        "address"   => "via Racalia, 150/A",
        "vat"       => "12589745896",
        "img"       => "millesapori.png",
        "types"     => [1],
    ],
    [
        "user_id"   => 14,
        "rest_name" => "NumberOne",
        "address"   => "Via Damusello, 137/E",
        "vat"       => "15784596324",
        "img"       => "numberone.png",
        "types"     => [1],
    ],
    [
        //14
        "user_id"   => 15,
        "rest_name" => "Dolci Peccati",
        "address"   => "Via Roma, 233",
        "vat"       => "12345678910",
        "img"       => "dolci-peccati.png",
        "types"     => [3],
    ],
    [
        "user_id"   => 16,
        "rest_name" => "Dolcemente",
        "address"   => "Via Trieste, 54",
        "vat"       => "2345678901",
        "img"       => "dolcemente.png",
        "types"     => [3],
    ],
    [
        "user_id"   => 17,
        "rest_name" => "Sole di Sicilia",
        "address"   => "Via Verdi, 82",
        "vat"       => "3456789012",
        "img"       => "sole-di-sicilia.png",
        "types"     => [3],
    ],
    [
        //17
        "user_id"   => 18,
        "rest_name" => "Misoshiro - Quasi solo Zuppe",
        "address"   => "Piazza Unità d'Italia, 10",
        "vat"       => "26373325657",
        "img"       => "misoshiro.png",
        "types"     => [4, 5],
    ],
    [
        "user_id"   => 19,
        "rest_name" => "Da Omar",
        "address"   => "Via Cala, 128",
        "vat"       => "81111403300",
        "img"       => "daomar.png",
        "types"     => [9, 10],
    ],
    [
        "user_id"   => 20,
        "rest_name" => "Castellana Pizze",
        "address"   => "Via Castellana Bandiera, 6/A",
        "vat"       => "43797553900",
        "img"       => "pizzacastellana.png",
        "types"     => [11, 1],
    ],
    [
        "user_id"   => 21,
        "rest_name" => "Palla di riso Tropicale",
        "address"   => "Via Nicolò Gallo, 1",
        "vat"       => "00671051036",
        "img"       => "palladiriso.png",
        "types"     => [12],
    ],
    [
        "user_id"   => 22,
        "rest_name" => "Kung Pow",
        "address"   => "Piazza Unità d'Italia, 10",
        "vat"       => "0018333416",
        "img"       => "kungpow.png",
        "types"     => [4, 9],
    ],
    [
        "user_id"   => 23,
        "rest_name" => "Samir e Gennaro",
        "address"   => "Via Sammartino, 14",
        "vat"       => "00971860344",
        "img"       => "samir.png",
        "types"     => [10, 1],
    ],
    [
        "user_id"   => 24,
        "rest_name" => "Riso Zen",
        "address"   => "Via Roma, 205",
        "vat"       => "00142650185",
        "img"       => "risozen.png",
        "types"     => [12, 5],
    ],
    [
        "user_id"   => 25,
        "rest_name" => "Da Totò",
        "address"   => "Via Giuseppe Pagano, 54",
        "vat"       => "00509106929",
        "img"       => "datoto.png",
        "types"     => [13],
    ]
];
